//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookHotel.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public System.DateTime RegisteredDate { get; set; }
        public decimal Price { get; set; }
        public int NumberOfBeds { get; set; }
        public int RoomId { get; set; }
        public bool Paid { get; set; }
        public System.DateTime BookFrom { get; set; }
        public System.DateTime BookTo { get; set; }
    
        public virtual Room Room { get; set; }
        public virtual User User { get; set; }
    }
}
